// Generated by Selenium IDE
/*
Test Case 02 Input Email pada Automated Helpdesk tidak sesuai format

Given User chatted the bot
*bot replied with email address form
When user input wrong email
*user click okay
Then nothing happened
*/
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCase02EmailTidakSesuaiFormatTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCase02EmailTidakSesuaiFormat() {
    driver.get("https://stockbit.com/");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.cssSelector(".intercom-launcher")).click();
    js.executeScript("window.scrollTo(0,500)");
    driver.findElement(By.name("message")).click();
    js.executeScript("window.scrollTo(0,500)");
    driver.findElement(By.name("message_field_identity-email")).sendKeys("testing testing testing");
    driver.findElement(By.linkText("OK")).click();
  }
}
