// Generated by Selenium IDE

/*
Testcase 001 If User try to login using google account but not registered yet

Given user have not logged in on stockbit 
* have no registered google account
When user login using google 
* not yet have registered google account
Then warning will be shown 'Maaf akun Google anda belum terdaftar sebagai pengguna Stockbit. Mohon mendaftar terlebih dahulu" 
* Move to register page 
* Fill the register page with user information
*/
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test01NoGoogleAccountTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test01NoGoogleAccount() {
    driver.get("https://stockbit.com/");
    driver.manage().window().setSize(new Dimension(976, 1040));
    driver.findElement(By.cssSelector(".button:nth-child(1) > .login-ldn")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".login-goog")).click();
    vars.put("win9407", waitForWindow(5000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win9407").toString());
    driver.findElement(By.cssSelector(".JDAKTe:nth-child(2) .w1I7fb")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
  }
}
